swagger: '2.0'
info:
  title: Snippets API
  version: v1
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /api/submitData/{id}/update/:
    patch:
      operationId: api_submitData_update_partial_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - api
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /api/submitdata/{id}/:
    get:
      operationId: api_submitdata_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - api
    parameters:
    - name: id
      in: path
      required: true
      type: string
  /mountains/:
    get:
      operationId: mountains_list
      description: ''
      parameters:
      - name: user__email
        in: query
        description: user__email
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Mountain'
      tags:
      - mountains
    post:
      operationId: mountains_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Mountain'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Mountain'
      tags:
      - mountains
    parameters: []
  /mountains/{id}/:
    get:
      operationId: mountains_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Mountain'
      tags:
      - mountains

    patch:
      operationId: mountains_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Mountain'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Mountain'
      tags:
      - mountains

    parameters: []
definitions:
  Mountain:
    required:
    - title
    - user
    - coord
    - level
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      beauty_title:
        title: Beauty title
        type: string
        maxLength: 255
      title:
        title: Title
        type: string
        maxLength: 255
        minLength: 1
      other_title:
        title: Other title
        type: string
        maxLength: 255
      connect:
        title: Connect
        type: string
        maxLength: 255
      add_time:
        title: Add time
        type: string
        format: date-time
        readOnly: true
      status:
        title: Status
        type: string
        enum:
        - NEW
        - PEN
        - ACC
        - REJ
      user:
        title: User
        type: integer
      coord:
        title: Coord
        type: integer
      level:
        title: Level
        type: integer
